import type { Hono, Context } from 'hono';
import { settings } from '@devvit/web/server';

// Acts as a simple proxy to start the Discord authentication flow.
// Returns a JSON object with the URL to the main Google Cloud Function, passing along the session ID generated by the client.
export const addDiscordStartRoute = (app: Hono) => {
  app.get('/api/auth/discord/start', async (c: Context) => {
    try {
      const DISCORD_AUTH_FUNCTION_URL = await settings.get('NEXT_PUBLIC_FIREBASE_DISCORD_AUTH_FUNCTION_URL');
      if (!DISCORD_AUTH_FUNCTION_URL || typeof DISCORD_AUTH_FUNCTION_URL !== 'string') {
        console.error('Auth Start Error: DISCORD_AUTH_FUNCTION_URL not configured');
        return c.json({ message: 'Server configuration error' }, 500);
      }

      const sessionId = c.req.query('sessionId');
      if (!sessionId) {
        console.error('Auth Start Error: Session ID is required');
        return c.json({ message: 'Session ID is required' }, 400);
      }

      // Construct the full URL to the Cloud Function, including the sessionId.
      const proxyUrl = new URL(DISCORD_AUTH_FUNCTION_URL);
      proxyUrl.searchParams.set('sessionId', sessionId);

      // Return the Cloud Function URL as JSON to be used by the frontend.
      return c.json({ authUrl: proxyUrl.toString() });

    } catch (error: any) {
      console.error('Discord auth start proxy error:', error.message);
      return c.json({ message: `Server error: ${error.message}` }, 500);
    }
  });
};